apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ceph-dashboard-route
  namespace: rook-ceph
spec:
  parentRefs:
    - name: edge-gateway
      namespace: kgateway-system
  hostnames:
    - ceph.oryzasa.site
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 8443
