apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rook-ceph-cluster
  - httproute.yaml
  - tlsroute-dashboard.yaml
configMapGenerator:
  - name: rook-ceph-cluster-values
    namespace: rook-ceph
    files:
      - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: ./helmrelease-patch.yaml
