apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pullsecret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflects: go-app,nodejs-app
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: go-app,nodejs-app
        reflector.v1.k8s.emberstack.com/reflect: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ILwPm6tzfWyoQgqVKsUVJhAGwE4lodKSXpbHPQ+laVz6PTHf0MYPU0dbAWMwUmJg8A0XA1Pr1PVlDlhj2fHvv/1b66uq+bRDbN4D2/4Xk9l6PU9ckrr/+u9zwTAlRd3jC/aasmplq3e7zXA0G1NTJdl/h1Q48OOC5632AedsQT7BwBjlkpRqp005NzeFmcUF,iv:8oBk2vdrIjGzlHChuGhxprFSJkG5T+j0a8bhyRpyXnU=,tag:prL2vcifPyViTjGrc56rZg==,type:str]
sops:
    age:
        - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVUIyaEp4SkI3YzNkSk1o
            Wk56MmVwRkJEU2JqdkFyMm5uU3hZR092Q1RJCitVMUowa3YwRkVxdGVGY3VQWFV3
            ZXNhRUx3MGdwbThBVjJQWmNOcExrNzQKLS0tIFVhQUp0bU1pV0N2d1dLTjAzL1U1
            WjY4bWthY21QSTFEblJSeDZ1Ynhob3MKOgzQh871BK4ygSh+8Zqbfk/wf2iZ7hTC
            +6Wue0TUBleW1vSk6jDLx2daKNzb/BGmxdVt8T/d6cVTO13+Ruk1jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T21:07:16Z"
    mac: ENC[AES256_GCM,data:cobBqdY+gkDptzMWvUB0UgKz8cIM/aka0dBTYYWkCzYd+QN652Zj5KK5ayJusIgNwSjQRo6z+5jkeiAhE3TfZYNpvTijuzXF5loGSwKcsx2rBV2its5w5BXCKaTRlasf3vvl/vmPIyZIF+IjFeAEx+Q7bzZL0RqdgVVp3JoHNfo=,iv:l/SfcbAkoBf0FuX4RZ3c1nLD3GFP6jjZmAJ4bzpogrM=,tag:6MnNTN8OOEab6+OW9CpvNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
