apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pullsecret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflects: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: go-app,nodejs-app
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:5lIGgFurPZDvTYyYRa4+964Wg6BQmP+9f9oZLmwMZ7rwYYb8rb+vNVgEHKjBVw+Z/8pmBnBw/UmUWIlC4r2O9uZrrAxln1Bnw3F/KICj89HjzxlyTfghh+Imk8mcCf6NR7LaWW8+AWmlw3XSI6yBk7aAMG7jCo1/OzsmYu914fromXCsEDgWkGAtuXj3jJFU,iv:utj/RnvoxM1X7wh/64xKIV5G+HXQz84HlKh783PCshg=,tag:vXIffDvQIYNFLD9N4moX/Q==,type:str]
sops:
    age:
        - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTN2SWFiMDFiMlNIYjkz
            V0tIN29UQjl1ejgxeDJ0VHp1VVVMZFdvL0R3CkZBN2phanJyNFRnRGxsMmdGNGNI
            ZG5UOEVnc2JYbU5xSW5kSGxzdWFHYlUKLS0tIHM4ZXFQUW1leklqOGQrZFNuRjZZ
            NFN2U2RnNE4yRlJxYVEzOEt3QytRRDgKsh2oW7JFMkmz11ncj6DXNsKQBBrX+ALF
            PmNDK86Mdq5t4yOW9kE0xKGmDEmBfCDXnJFg2Ky+LDKKAwqSyjDuvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T20:10:45Z"
    mac: ENC[AES256_GCM,data:YSN9C5anHfEeF4aj/rmd64IxYmsUG/OQEu8W8rUejDvpyUnwglmX8NGVlfsMQcuVb2TExltTsK6t2rE0c7lnouy5+KdEQQDo1raleDE5FnXysrsMkAF5AaL0yWZ51ypUe3lCpLJ1yNkYeDcGbh3jRjVztF8n8BxQ8PmlQY2Z+TM=,iv:a3xOVXf/XtMa/iFj1MB/kbaa+UeVyi6Qpj1D9bVn5ow=,tag:LjXN3CvzgjTLG2AA53Imiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
