apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pullsecret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: go-app,nodejs-app
        reflector.v1.k8s.emberstack.com/reflects: go-app,nodejs-app
        reflector.v1.k8s.emberstack.com/reflect: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:TkVXE+SdM85jUmcvwrZr5UKb1JpOP6/YB1pMhuM9mJmfrbxHPKaFE/ovL+s3ArOGDL+VHURqfeUjRJdUWrrO4Rwz+ch7MNp5VpDlsKhpk5P25xta5lTdg4QtjZXJi9slnErZ9ap0LGd9PCfZhh8jNkdpBxnNMATgBMzvdo4O1Xsl17xjC2oiM9lTsOcT4TQv,iv:J5yduR+WTXDLig32A7TVgrtJkOdmm714HhuhVAGux7U=,tag:/XZO52byVXds3d1Uz2w8fQ==,type:str]
sops:
    age:
        - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbFlHL3hYRUR5WnJpMzZ3
            QmVJT2hjUU4vS0JtdVEvZmhFTzRuaUJIOHc0CmZVSEk4dmtJNHZqYXFJMitKbjJa
            L2dHRm81c1c4UGJhMlV1SEdRZWlSTkUKLS0tIHV2ZURNaDdZQ295S0xyeXVZMW9B
            UWN3NHFpRlhFV2praWU1RmI0Rkt6ZnMKGKvNr2GajpZt+teL0E6TibRYiUHlNZUe
            vJSGEnu/g6Sm9uIpLXxZ8yDsdDCzz2Db5lu4V6jWPAjBJ06EARThjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T20:50:19Z"
    mac: ENC[AES256_GCM,data:4iQE4HuhQiGEcRzAtUNAxn5qINi1Px0mTbaHQIlddZzj32bT6G+wETCrkaVfYmYDyZZXLGUQt8tVXfF3cPkEvcGlquUJzugeMPcTYNKHgjpoufAnCbkTmwiafE4+SdjK7V689Otp+LPJacgHgUTBjMpuJNG6eE5itLG2YFLCXGM=,iv:RPiB5XWRQrf/5hrg2ft1u1lxDdEb9cfxi0yoinH+Vps=,tag:OghHrqiOq1pWXT+Pr+OXoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
