apiVersion: v1
kind: Namespace
metadata:
  name: go-app
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-app
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
