apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pullsecret
    namespace: go-app
    annotations:
        kubernetes.io/service-account.name: default
    labels:
        app.kubernetes.io/name: ghcr-pullsecret
        app.kubernetes.io/part-of: go-app
        managed-by: gitops
        reflector.v1.k8s.emberstack.com/disabled: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6x7MJm8hHzX9sb0a0b+vYrLjyYPFY7HSxSWF7D4idT0uZHKE5pPJL7zGeFV+nm7Q+9MqrWKXiYpWXGc9EQ0Rxl4YWSBVsHsLRwUsz1aHwLzEyoIKJhqEJGBWVQJzudvJ0t2Q+rsBDiIOs6lSN8mqjFJToou0IOY6tMnjyvX03HUvvnKf124yLccSAlQfJG5T,iv:jLcS3LgNNLrPssEmWS2dhWxHZ51PNk5OufSZnb2rhgw=,tag:TsQbykweIrKqsBDVHOWfuA==,type:str]
sops:
    age:
        - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYnB0OXZMK0xBOFI5K2oy
            NURlbXFRZWRHSkpKWmZGWGZBazVEeHZPRXhFClZnb2FTM2Y1TldiZkZrSUNvcVk4
            Q3ZjSmJHOTdNUXFsclV0SjRmWU0wdmcKLS0tIHU4d2dkM1B1aWV0aDliUzRNNHgy
            ajhlMUt2cHpRQ0o5c25YNGZLVUZjNjgKfEKyMiRUvv5BXWLsZeIAgSqTTdS+oC09
            1gAYZr9gKvFbMQOIrJFVTI2avw9WVS4zZr+T8rdTaL0tGWHYRbodIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T21:08:46Z"
    mac: ENC[AES256_GCM,data:QKRXt3TJ26o540KG1N91bjWwK9jcdGP+4sPFmg4cD/vJe9UEnDfiJ9hG74a0JXOaRvipA4DKbkzCEO9ZNdrB1gwsmfj9hy/hCd3ZQDlSPOIPhfdngSJS1JbrYGlKfGFaVApioNiJq93y/0n0pOHHlhM46+2mNphGVqPuX+ZTLow=,iv:IqsZpZqDca0oUT9Fhwe7nka66I9MfmH2Qcn8Q+3lGbs=,tag:Pj4jlGSHT0FGORYsVWzEwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pullsecret
    namespace: nodejs-app
    annotations:
        kubernetes.io/service-account.name: default
    labels:
        app.kubernetes.io/name: ghcr-pullsecret
        app.kubernetes.io/part-of: nodejs-app
        managed-by: gitops
        reflector.v1.k8s.emberstack.com/disabled: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:+crw7OZ11kJbg4UFu/JYh4RL1sN6/vkdulE5NuJ5oFzLRZofRuDWUHTNQavVhdE7D3/FMGBOyRzo/NxHWyFB9yxhVKTZBM/o2I0DTYkDjuVIeyMzfWLD1w+lqHq1Jw9n0bqvl0yNkE41J4FHrUxfogw7Ygz/ulccPOEp5/HwUKvA0hCKPIMNwZpCT5kUhcWI,iv:FsdLp16OUd2j9PfboQMUHNgnBUaHlH9IwAiAyZVB6kY=,tag:Hn1b1wMgC7yGr4nZLBJ0MQ==,type:str]
sops:
    age:
        - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYnB0OXZMK0xBOFI5K2oy
            NURlbXFRZWRHSkpKWmZGWGZBazVEeHZPRXhFClZnb2FTM2Y1TldiZkZrSUNvcVk4
            Q3ZjSmJHOTdNUXFsclV0SjRmWU0wdmcKLS0tIHU4d2dkM1B1aWV0aDliUzRNNHgy
            ajhlMUt2cHpRQ0o5c25YNGZLVUZjNjgKfEKyMiRUvv5BXWLsZeIAgSqTTdS+oC09
            1gAYZr9gKvFbMQOIrJFVTI2avw9WVS4zZr+T8rdTaL0tGWHYRbodIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T21:08:46Z"
    mac: ENC[AES256_GCM,data:QKRXt3TJ26o540KG1N91bjWwK9jcdGP+4sPFmg4cD/vJe9UEnDfiJ9hG74a0JXOaRvipA4DKbkzCEO9ZNdrB1gwsmfj9hy/hCd3ZQDlSPOIPhfdngSJS1JbrYGlKfGFaVApioNiJq93y/0n0pOHHlhM46+2mNphGVqPuX+ZTLow=,iv:IqsZpZqDca0oUT9Fhwe7nka66I9MfmH2Qcn8Q+3lGbs=,tag:Pj4jlGSHT0FGORYsVWzEwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
