apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespaces
  - ../../base/sources
  - ./rook-ceph-operator
  - ./rook-ceph-cluster
  - ./cnpg-operator
  - ./cnpg
  - ./harbor
