apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - harbor
configMapGenerator:
- name: cnpg-values
  namespace: database
  files:
  - values.yaml=./cnpg/values.yaml
- name: rook-ceph-cluster-values
  namespace: rook-ceph
  files:
  - values.yaml=./rook-ceph-cluster/values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
- path: ./cnpg/helmrelease-patch.yaml
- path: ./rook-ceph-operator/helmrelease-patch.yaml
- path: ./rook-ceph-cluster/helmrelease-patch.yaml
