apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nodejs-app
resources:
  - ../../nodejs-app/deployment.yaml
  - ../../nodejs-app/httproute.yaml
  - ../../nodejs-app/service.yaml
