apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nodejs-app
resources:
  - ../../../deploy/apps/nodejs-app/deployment.yaml
  - ../../../deploy/apps/nodejs-app/httproute.yaml
