apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rook-ceph/repository.yaml
  - ./cnpg/repository.yaml
  - ./harbor/repository.yaml
  - ./metallb/repository.yaml
  - ./kgateway-crds/repository.yaml
  - ./kgateway/repository.yaml
  - ./prometheus/repository.yaml
