apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: go-app-route
  namespace: go-app
spec:
  parentRefs:
    - name: edge-gateway
      namespace: kgateway-system
  hostnames:
    - go.oryzasa.site
  rules:
    - backendRefs:
        - name: go-app
          port: 3000
