apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nodejs-app-route
  namespace: nodejs-app
spec:
  parentRefs:
    - name: edge-gateway
      namespace: kgateway-system
  hostnames:
    - node.oryzasa.site
  rules:
    - backendRefs:
        - name: nodejs-app
          port: 3000
