apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-secret
  namespace: harbor
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:irtmUNyPQGS+ABLJEKkqag==,iv:sVlkny+72oY/gPRKK66/sqS/5LdVROJ5nWwI29SmwRQ=,tag:L10b8cjLV9ILXVnYXFtgDg==,type:str]
sops:
  age:
    - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ05FMlBoaGNUanptYkNw
        OVFma1N0cHZyNGlMcWtsTDRIUEZxWWlod0IwCnoyakR0WVpmd2p5TzhvcjU2WTZp
        U1dUdExjWnR5QUJEQVVhV3VQS2FIQ1EKLS0tIGRrQmdmWkt2NTVxT3NFbWFPSFAx
        YWlWNkhBeldlejVhQ0VWN2U1QXdwOXcKyL5nlvipfAM69CAV5tmPxElIzj+ca5xo
        twSPItWHSyLlW1ygZRPcHD53GjfDusZg9JuQyngwnGOpCOPonTZ71w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T03:39:54Z"
  mac: ENC[AES256_GCM,data:1D6YNW0O28JPyDaI8d2OreRPb4xH9qx+DN1uRb2gQENbalKphdGCAgUWoIQGPj5zC3GhNaLiwi91buKO45SabMKfVbvyNRuiT01HfhT7PAr6fLxQfD8LiHH5HrdFdYltQjJLzEpsa5KCIVn7rmYgv3MNvjSdyENU6pShg5DIclM=,iv:ZIvvppXZX2kFbKOEcAcO6pXI/ALspN4LbCs2d85jSxo=,tag:P4/0RW/ba9phwdtGo9zOjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
