apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-route
  namespace: harbor
spec:
  parentRefs:
    - name: edge-gateway
      namespace: kgateway-system
  hostnames:
    - harbor.oryzasa.site
  rules:
    - backendRefs:
        - name: harbor
          port: 80
