apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: harbor-values
  namespace: harbor
  files:
  - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true
