apiVersion: v1
kind: Secret
metadata:
  name: harbor-database
  namespace: harbor
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:t2NfmoBmwq7A1GzKZkVs+9z8vLgv9x2edWx6xlNgCig+JuxLz7WtqJtdCzHdyfBqWZytgLx05/VptWyQ8KqnjQ==,iv:pX4YwUuVCOlor13ns1AGBVtYT4VaAaNnFQRmJidy25c=,tag:wkrzzKz1enBryf4g5lbBGA==,type:str]
sops:
  age:
    - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoczdNMS90N0t0Ykg4bis2
        QmRKZ01IRnlOTTBvVWYvSThCQ3ZNaDJrMmdJClFuLzdnSTJPd0ZDaS9FVHU5cTdF
        UWJwVnRCSzZFSm9Va3pSdXpCZHFCcEkKLS0tIHlFOGlBSnNzTkE3V2IyZHhuQjh0
        WTErNkNkbDJ5VTMvSHlsZG4xemluNk0Kxvnl54d7bPVxYgVNqiN09vA3T74uI7Bw
        pSq3mRtlU0fr+VQdtw/WQQGBNI9GtM1awZZoll5VCoIgREowBLJQyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T06:12:09Z"
  mac: ENC[AES256_GCM,data:XMzdQ9gz0158JSd7P90tD3L42hrusXxF5HK7TirPBZfXYdW08Vr5S9nY0q6mBDZ3idKGoa6W6N55V2bQ5vQ5iWGB3Hn1muiq8oevPyemIE8M7VMdNDPt0/MIX3kCR7cQlBCx+8kupafzDlUuxgXzP4W9+QZhDVk3gd85DK9ZMz8=,iv:pIA9zcd3zBOhYolEK3KOsumVf5iLLhPNI5NB6J5kP9I=,tag:RWXheSZr8lws5MqKt3x9Ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
