externalURL: http://harbor

expose:
  type: clusterIP
  tls:
    enabled: false

database:
  type: external
  external:
    host: cluster-rw.database.svc.cluster.local
    port: 5432
    username: postgres
    existingSecret: harbor-database
    sslmode: disable

redis:
  type: internal

persistence:
  persistentVolumeClaim:
    registry:
      size: 150Gi
