apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rook-ceph/namespace.yaml
  - ./cnpg-system/namespace.yaml
  - ./cnpg/namespace.yaml
  - ./harbor/namespace.yaml
  - ./metallb-system/namespace.yaml
  - ./cloudflared/namespace.yaml
  - ./kgateway-system/namespace.yaml
