apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: edge-gateway
  namespace: kgateway-system
spec:
  gatewayClassName: kgateway
  addresses:
    - type: IPAddress
      value: 10.200.250.200
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.oryzasa.site"
      allowedRoutes:
        namespaces:
          from: All
