apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:ZROHIPb1T5/TNjlcRpR9eVVK3p43LP4UjRKm0KTI98BZzfkgl+iMlRWn2PxqyPKn3nWDC7Xgk+GQIkhPM90Eps0UPvBW4JPa3Dk/UAtWpdP8Rpg8UpzO9vUTtKFe0JHoQ5IZM0guiSX1QbxD+BTTj8C3VNmOqehVyXTPe0RtHafJNvubzZ6ZAVNFR480+DZPV4oqf1ULfLt1Pt1DXDNfcaIttyO+jQ4zRAe5c/o94belVTHd,iv:1plqz0REe3VOmTmTKFHVWhPTSVy1ryEn3aoewJQTY+c=,tag:a1JNhyq7B5dBa6k5tyH7/Q==,type:str]
sops:
  age:
    - recipient: age156xfc5w7nfn7ls24mg82gmjr7vzefpfvdsnxcfync7qfkpwxzals530asy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYWxiM2IzRVRBWFBYWnRB
        M0hFaXNXZHdtb2lqRjgrSmx6ZFdJbDRxekhBCkVWc2xGTDN2MDFTbGNHMDN1OUdT
        NlBwalFya1o0TkptWVluVlNVZXZpc0EKLS0tIDJVa3JKTE5ZcGVVcEVDNEUxMUQr
        UGNvNDFwbEhvNkNrNUs5eFo1MlhNZ1EKjkBI/eIz4pszJh29lFVBHp22DF1ijI2E
        jq6qzTzkHU3wGTS+rfuS0SAJsZrq5e++LCD6x+oAawddPs4TXRr2EQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T00:09:25Z"
  mac: ENC[AES256_GCM,data:YLSvxlXlkTushkFJxra8R7ThDhjkZz53TlNWpYVeOrNE5HJucu5AwWh3beK1n3PKDqqZhdW4DugKEBLL+egxnKwpsU0x1Kfw0UcJrZsVkRWMvHICAzL+d0hdS+cYkGMxRFZR3tL1ie6CMQb3OqrqyIar/EAPfi/efvLSeit90tg=,iv:S61R4Qhd0BSKRgwcdNQ+9jDHI1mKD/dbEp3GMOlAEw0=,tag:Ewn++ZTJojKoU6VnlNr+rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
