apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces
  - ./sources
  - ./rook-ceph-operator
  - ./rook-ceph-cluster
  - ./cnpg-operator
  - ./cnpg
  - ./harbor
  - ./gateway-api
  #- ./cloudflared
  - ./metallb
  - ./kgateway-crds
  - ./kgateway
