apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cnpg
configMapGenerator:
  - name: cnpg-values
    namespace: database
    files:
      - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: ./helmrelease-patch.yaml
